"""empty message

Revision ID: 94f08e696638
Revises: 35d630e708d9
Create Date: 2026-03-18 00:42:28.035798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94f08e696638'
down_revision = '35d630e708d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plane', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plane_callsign'))
        batch_op.create_index(batch_op.f('ix_plane_callsign'), ['callsign'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plane', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plane_callsign'))
        batch_op.create_index(batch_op.f('ix_plane_callsign'), ['callsign'], unique=1)

    # ### end Alembic commands ###
