"""planedata table

Revision ID: c41552ffbd52
Revises: d7fca3d762d1
Create Date: 2026-02-27 23:16:30.674586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c41552ffbd52'
down_revision = 'd7fca3d762d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plane_data', schema=None) as batch_op:
        batch_op.alter_column('time_position',
               existing_type=sa.INTEGER(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.drop_column('category')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plane_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.INTEGER(), nullable=False))
        batch_op.alter_column('time_position',
               existing_type=sa.DateTime(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
