"""planedata table

Revision ID: d7fca3d762d1
Revises: 
Create Date: 2026-02-27 15:27:48.174429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7fca3d762d1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plane_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('time_fetched', sa.DateTime(), nullable=False),
    sa.Column('icao24', sa.String(length=10), nullable=False),
    sa.Column('callsign', sa.String(length=10), nullable=True),
    sa.Column('origin_country', sa.String(length=60), nullable=False),
    sa.Column('time_position', sa.Integer(), nullable=True),
    sa.Column('last_contact', sa.DateTime(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('baro_altitude', sa.Float(), nullable=True),
    sa.Column('on_ground', sa.Boolean(), nullable=False),
    sa.Column('velocity', sa.Float(), nullable=True),
    sa.Column('true_track', sa.Float(), nullable=True),
    sa.Column('vertical_rate', sa.Float(), nullable=True),
    sa.Column('sensors', sa.JSON(), nullable=True),
    sa.Column('geo_altitude', sa.Float(), nullable=True),
    sa.Column('squawk', sa.String(length=100), nullable=True),
    sa.Column('spi', sa.Boolean(), nullable=False),
    sa.Column('position_source', sa.Integer(), nullable=False),
    sa.Column('category', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plane_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plane_data_callsign'), ['callsign'], unique=False)
        batch_op.create_index(batch_op.f('ix_plane_data_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_plane_data_icao24'), ['icao24'], unique=False)
        batch_op.create_index(batch_op.f('ix_plane_data_origin_country'), ['origin_country'], unique=False)
        batch_op.create_index(batch_op.f('ix_plane_data_time_fetched'), ['time_fetched'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plane_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plane_data_time_fetched'))
        batch_op.drop_index(batch_op.f('ix_plane_data_origin_country'))
        batch_op.drop_index(batch_op.f('ix_plane_data_icao24'))
        batch_op.drop_index(batch_op.f('ix_plane_data_created_at'))
        batch_op.drop_index(batch_op.f('ix_plane_data_callsign'))

    op.drop_table('plane_data')
    # ### end Alembic commands ###
